### PR TITLE
Port to Python 3

### PR DESCRIPTION
**Pull request by pro-panda**
Since our em.py is the same as upstream, it can be removed

### CODE REVIEW

**Comment by quozl** [comment]
Related to https://github.com/sugarlabs/sugar-artwork/issues/102

(For excellent communication, please link pull requests to issues where appropriate.)

**Comment by Pro-Panda** [comment]
> (For excellent communication, please link pull requests to issues where appropriate.)

Noted. Thank you

**Comment by Pro-Panda** [comment]
> With 49f85c9 removing em.py, and 798d2da showing Fedora packaging uses our embedded em.py,
> could you update the commit message to add a note that the Fedora packaging will have to use the
> upstream em.py? Then I'll see that during release and add it to release notes.

Thank you, done. 
But will there be an advantage in embedding it rather than always using upstream ?

**Comment by quozl** [comment]
> will there be any advantage in embedding it rather than always using upstream ?

I don't know of any advantage other than being shielded from changes to em.py, but at the stage of evolution of em.py such changes seem unlikely.

Please also fix the Makefile.am files as they use $(srcdir) to find em.py.  The Debian or Ubuntu package has a diff you can use or check against.

Please also test building the sugar-artwork package.  It should have failed due to above.

**Comment by Pro-Panda** [comment]
> Please also fix the Makefile.am files as they use $(srcdir) to find em.py. The Debian or Ubuntu 
> package has a diff you can use or check against.

Thank you. done.

> Please also test building the sugar-artwork package. It should have failed due to above.
Yes, sorry. I didn't test earlier.
Build logs [here](https://gist.github.com/Pro-Panda/19476e47360864a3b952004681f07204)

**Comment by quozl** [comment]
Thanks.  Reviewed to c1df512.

**Comment by quozl** [comment]
Thanks.  Reviewed to 900f708.

**Comment by Pro-Panda** [comment]
@quozl 
What should be the next steps ?
I have tested these packages: [Pro-Panda/sugar-artwork-packages](https://github.com/Pro-Panda/sugar-artwork-packages)

**Comment by quozl** [comment]
Thanks.

You might use `debdiff` to compare your binary packages with the Debian or Ubuntu binary packages that were built by Debian or Ubuntu from the same source package.  This will help to isolate any unexpected changes in binary form.

Otherwise, next step according to https://github.com/sugarlabs/sugar-artwork/issues/102 is to build Fedora packages, and then call for testing by others using a public announcement.

We should hold back from public announcement until each of the other repositories in the project reach the same point; _sugar_, _sugar-datastore_, and _sugar-toolkit-gtk3_.  Also, packages for _sugar-toolkit-gtk3_ could be immediately used by activity developers.

**Comment by Pro-Panda** [comment]
> We should hold back from public announcement until each of the other repositories in the project reach the same point; sugar, sugar-datastore, and sugar-toolkit-gtk3. Also, packages for sugar-toolkit-gtk3 could be immediately used by activity developers.

Noted, thanks

**Comment by Aniket21mathur** [comment]
@quozl @pro-panda . Tested building, built successfully. What should we do next?

**Comment by quozl** [comment]
Thanks.  Resolved conflicts and merged as https://github.com/sugarlabs/sugar-artwork/commit/29fc56cbbfc49af1f7c8c0930814ad174dc898f5.

**Pull request closed without merging**
