### PR TITLE
Add palette-modal icon; an indicator that a PaletteMenuItem has a modal

### PR DESCRIPTION
**Pull request by samdroid-apps**
Feature page:  http://wiki.sugarlabs.org/go/Features/Replace_GtkMenu

### CODE REVIEW

**Comment by godiard** [comment]
@samdroid-apps, Maybe we should use "..." in the label when a modal dialog will be opened. This is a convention used in other environments.

**Comment by samdroid-apps** [comment]
@godiard In all of the designs on the wiki they use an arrow <http://wiki.sugarlabs.org/go/Design_Team/Designs/Frame> <http://wiki.sugarlabs.org/go/Design_Team/Designs/Journal#mediaviewer/File:Journal-04.jpeg>.  It looks very simple and refined and still portrays that there is something coming after clicking the button.

That's my opinion, but happy to change if needed :smile:

**Comment by godiard** [comment]
@samdroid-apps, used arrows because used submenus :)

**Comment by samdroid-apps** [comment]
Gnome uses arrows to indicate many different non-submenu things:




So does Firefox:



And iOs:

photo

**Pull request closed without merging**
