### PR TITLE
Removed icon-slicer dependency

### PR DESCRIPTION
**Pull request by ezequielpereira**
- Replaced icon-slicer with Xcursorgen
- Split the cursor images into individual images
- Fixes SL#3143 (https://bugs.sugarlabs.org/ticket/3143)
- This is a GCI 2015 task: https://codein.withgoogle.com/tasks/6222595863085056/

### CODE REVIEW

**Comment by quozl** [comment]
Nak.  Would break build.  You don't appear to have replaced icon-slicer with anything else.  It isn't enough to just remove it, you still have to process the icons.

**Comment by samdroid-apps** [comment]
Hi @ezequielpereira ,

What did you do to remove the dep?  Specifically, why is git counting the images are different?  What is replacing icon slicer?  Please explain that in your commit message.

Also, please link to the bugs.slo ticket rather than the gci task!

**Comment by ezequielpereira** [comment]
@samdroid-apps done.

**Comment by samdroid-apps** [comment]
Sorry for not reviewing this.  This change looks awesome.

Xcursorgen is part of the xorg-x11-apps package.  It seems like it won't be dropped, but I really don't know enough about this.  @ezequielpereira do you remember why you chose this?  Is anybody else using it?

Also, you removed the makefile dependency check for icon slicer.  Can you add one for Xcursorgen in replacement?

**Comment by ezequielpereira** [comment]
I chose it because it was the only way I found online.
I found it being used here: [adwaita-icon-theme](https://github.com/GNOME/adwaita-icon-theme/blob/7f9e8f3f97fd2665f2453aed09ef678f50e6fa2a/src/cursors/pngs/make.sh)

I guess I should add xorg-x11-apps to the dependency, how do I do that? (I never used Makefiles really)

**Comment by samdroid-apps** [comment]
Sorry I said makefile, it turns out that I actually meant configure.ac file.  In your patch, you removed from configure.ac:

```
 AC_PATH_PROG([ICON_SLICER], [icon-slicer])
 if test -z "$ICON_SLICER"; then
     AC_MSG_ERROR([icon-slicer is required])
 fi
 
```

Maybe you need to have something like that, but with Xcursorgen.

Also if adwainta is using Xcursorgen it is probably the right thing to use.

**Comment by ezequielpereira** [comment]
I don't know how to test for it in the configure.ac, maybe someone else you can help me with that :-/

**Comment by quozl** [comment]
I can help you by showing you what to read to learn how to do it yourself.

* https://en.wikipedia.org/wiki/GNU_build_system (especially the flow diagram and the external links),
* https://help.ubuntu.com/community/CompilingSoftware

And in a clone of sugar-artwork repository;
* review autogen.sh, and then run it,
* use "make distcheck" which will generate .tar.xz files,
* continue with "configure" and "make",

You might also be interested in:
* the Fedora packaging specification file http://pkgs.fedoraproject.org/cgit/rpms/sugar-artwork.git/tree/sugar-artwork.spec which follows the flow diagram from the "configure' step,
* the Debian packaging rules file for the sugar-artwork package in Debian or Ubuntu, which also follows the flow diagram from the "configure" step.

**Comment by i5o** [comment]
Should we close this?

**Comment by quozl** [comment]
It needs work to add Xcursorgen to configure.ac, that's all.  You or someone might take the commit above and extend it.

Will also require testing using configure.ac, which is packaging testing, not just sugar-build.

**Comment by Pro-Panda** [comment]
> It needs work to add Xcursorgen to configure.ac, that's all. You or someone might take the commit above and extend it.

@quozl, I can't understand the changes in the images. Should they be kept ?

> Good chance of some files having changed since the pull request was raised. They won't be flagged as conflicts if they are new. Check for new files since.

What needs to be done regarding the new files added since ?

**Comment by Pro-Panda** [comment]
Closing; continued in #107

**Pull request closed without merging**
