### PR TITLE
Fix treeview background, fixes #4855

### PR DESCRIPTION
**Pull request by samdroid-apps**
This also therefore fixes #4857

Main ticket:  http://bugs.sugarlabs.org/ticket/4855
Journal ticket:  http://bugs.sugarlabs.org/ticket/4857

@walterbender could you test if this breaks anything on fedora 19?

### CODE REVIEW

**Comment by samdroid-apps** [comment]
@walterbender just tested and it didn't seem to break

**Comment by godiard** [comment]
@samdroid-apps. should we keep the old rule for backward compatibility? Was tested on F18?

**Comment by samdroid-apps** [comment]
The old rule seems to break the newer versions.

It was not tested on F18... But do we still support that?

**Comment by quozl** [comment]
Let me know when you drop support for Fedora 18 and I'll fork all the repositories.  ;-)

**Comment by tchx84** [comment]
@samdroid-apps yeah, we still support it... a lot of users still run Sugar on top of fc18.

**Comment by samdroid-apps** [comment]
OK.

Would somebody be able to test on f18; I do not have access to an
installation?

**Comment by quozl** [comment]
Sure, please check my test method:
* apply the patch by hand to /usr/share/themes/sugar-{72,100}/gtk-3.0/gtk-widgets.css
* restart desktop,
* verify background in Log Files widget.

This is what it looks like on Fedora 18:

screenshot of _log activity_

So you will probably have to write a conditional wrapper in the .css.em files, so use GTK_VERSION, discovered by configure.ac, substituted in gtk3/theme/Makefile.am.  Let me know if you have any questions on that.  GNU autotools for the win.

**Comment by samdroid-apps** [comment]
Replacing...

**Pull request closed without merging**
