### PR TITLE
Fixed description icon not visible

### PR DESCRIPTION
**Pull request by SudoSu-bham**
The description icon was not rendering for any of the activity, I have checked and found that problem was with [edit-description.svg](https://github.com/sugarlabs/sugar-artwork/blob/master/icons/scalable/actions/edit-description.svg). I have made changes to the `edit-description.svg`  and tested with sugar desktop environment (in Debian) and sugar live build the icon was visible in both after the change.

Fixes sugarlabs/sugar-toolkit-gtk3#465
The Screenshot below depicts the same
Screenshot from 2024-04-06 00-38-14

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  What did you change?  I've looked at the diff, but I don't understand the nature of the change yet.  I need to understand so that I can prevent unintended side effects.  Also, how did the problem happen?  It was last changed in 2012, and was working fine.

**Comment by SudoSu-bham** [comment]
The problem was with the line 7 of `edit- description.svg`
 https://github.com/sugarlabs/sugar-artwork/blob/master/icons/scalable/actions/edit-description.svg#L7
 The `viewBox` attribute was causing the problem after removing `px` from the coordinates of viewBox, The icon rendered properly.
 
 How I did
 I compared the content of some svg from the sugar-artwork icons
 After that I used photoshop and without making any changes to `edit-description.svg` just saved the file which gave new `<path>` (svg paths are used to create shapes). The new svg was normal and rendered correctly.
 After that I ported the new svg file with reference to previous one and made it compatible with [sugar svg template](https://wiki.laptop.org/go/Making_Sugar_icons).
 
 I also found out that just removing `px` from the coordinates of viewBox of original `edit- description.svg` can also do the work. Should I modify my commit? Or we can use the new SVG file from my PR which is working properly and tested with sugar.

**Comment by chimosky** [comment]
Your commit message can be improved to include some of the comments you just made, as it includes what you thought was the problem and the solution.

**Comment by quozl** [comment]
Thanks.  Does the fix work with only the viewBox change?  There are other changes in the file.

**Comment by SudoSu-bham** [comment]
The new file has only some changes `<path>` and removal of `px` from all attributes. The reason for difference in `<path>` is because the new file has been made using Photoshop.

Yes, the fix worked by just changing the `viewBox` in Kali Linux 2024.1. but before making a PR, I always check on different systems Kali Linux, Fedora 39, Ubuntu 22.04 LTS, and Sugar live build. I can't test it now because I have exams. I'll check it after 2 days and let you know if it's compatible everywhere or not.

**Comment by quozl** [comment]
Good, thanks.  Don't think we need changes from Photoshop.  Commit added: 7efad05971afc05e90048fb90d5ece75f5d9ba31.

**Pull request closed without merging**
