### PR TITLE
Revert "Revert "Revert feet logo""

### PR DESCRIPTION
**Pull request by i5o**
Reverts sugarlabs/sugar-artwork#98

http://lists.sugarlabs.org/archive/sugar-devel/2017-September/054710.html
The motion passed
https://wiki.sugarlabs.org/go/Oversight_Board/Decisions#2017-09-15

### CODE REVIEW

**Comment by icarito** [comment]
Has the SFC responded whether or not Sugar Labs has a right to distribute this logo? My concern is still valid.

**Comment by godiard** [comment]
i5o, also, even when this change is needed, we asked @icarito not push his own changes because is a community rule. Please don't do the same.

**Comment by i5o** [comment]
My bad @godiard.

Perhaps we should leave no icon meanwhile? :)

**Comment by godiard** [comment]
@i5o, I don't know. Maybe you can try propose add the functionality of change the icon to Sugar (without need add a activity). Should not be too difficult include the functionality of "Icon change" (http://activities.sugarlabs.org/en-US/sugar/addon/4683) as a control panel option.

**Pull request merged**
